version: 2.1

orbs:
  browser-tools: circleci/browser-tools@0.1.3
  anchore: anchore/anchore-engine@1.8.4

anchors:  # Moved anchors section to the top
  run_test_aws_access:
    run:
      name: Test AWS access
      command: |
        apk add --update aws-cli bash
        aws sts get-caller-identity
        aws ecr get-login-password --region ${AWS_REGION} | docker login --username AWS --password-stdin $AWS_ACCOUNT_ID.dkr.ecr.${AWS_REGION}.amazonaws.com
  set_env_vars:
    deploy:
      name: Set environment variables
      command: |
        account_id=$(aws sts get-caller-identity --output text --query "Account")
        region=${AWS_REGION}
        image_tag="${account_id}.dkr.ecr.${region}.amazonaws.com/eq/ruby-base-image:${CIRCLE_SHA1}"
        echo "export account_id=$account_id" >> $BASH_ENV
        echo "export region=$region" >> $BASH_ENV
        echo "export image_tag=$image_tag" >> $BASH_ENV

jobs:
  docker-build-image:
    executor: anchore/anchore_engine
    shell: "/bin/bash -eo pipefail"
    steps:
      - setup_remote_docker:
          docker_layer_caching: true
      - checkout
      - <<: *run_test_aws_access
      - <<: *set_env_vars
      - run:
          name: Build SkyMap Base Image
          command: |
            echo $image_tag
            docker build --tag $image_tag .
      - anchore/analyze_local_image:
          image_name: $image_tag
          policy_failure: False
          timeout: 500  # Ensure timeout is an integer
      - deploy:
          name: Push docker-images to ecr with only the commit and latest tag
          command: |
            aws ecr get-login-password --region ${region} | docker login --username AWS --password-stdin $AWS_ACCOUNT_ID.dkr.ecr.${region}.amazonaws.com
            docker push "${image_tag}"
            ecr-retag "$1" "$2" "$3"

workflows:
  version: 2
  commit:
    jobs:
      - docker-build-image

  scheduled-workflow:
    triggers:
      - schedule:
          cron: "0 12 * * 1"
          filters:
            branches:
              only:
                - ruby-2.7.1
    jobs:
      - docker-build-image
