version: 2.1
orbs:
  browser-tools: circleci/browser-tools@1.4.6
  anchore: anchore/anchore-engine@1.9.0
run_test_aws_access: &run_test_aws_access
  run:
    name: test aws access
    shell: "/bin/sh -eo pipefail"
    command: |
      apk add --update aws-cli bash
      aws sts get-caller-identity 
      `aws ecr get-login --no-include-email --region ${AWS_REGION}`
set_env_vars: &set_env_vars
  deploy:
    name: set env variables
    command: |
      account_id=$(aws sts get-caller-identity --output text --query "Account")
      region=${AWS_REGION}
      image_tag="${account_id}.dkr.ecr.${region}.amazonaws.com/eq/ruby-base-image:${CIRCLE_SHA1}"
      echo "export account_id=$account_id" >> $BASH_ENV
      echo "export region=$region" >>  $BASH_ENV
      echo "export image_tag=$image_tag" >>  $BASH_ENV
      
jobs:
  docker-build-image:
    executor: anchore/anchore_engine
    shell: "/bin/bash -eo pipefail"
    steps:
    - setup_remote_docker:
        docker_layer_caching: true
    - checkout
    - <<: *run_test_aws_access
    - <<: *set_env_vars
    - run:
        name: Build SkyMap Base Image
        command: |
          echo $image_tag
          docker build --tag $image_tag .
    - anchore/analyze_local_image:
        image_name: $image_tag
        policy_failure: False
        timeout: '500'
    - deploy:
        name: Push docker-image to ECR with commit SHA1 tag
        command: |
          docker push ${image_tag}
    - deploy:
        name: Retag image with SHA1 and latest tag
        command: |
          function retag_image {
            local image_uri=$1
            local sha1_tag=$2
            local latest_tag=$3
            docker tag $image_uri $image_uri:$sha1_tag
            docker tag $image_uri $image_uri:$latest_tag
          }
          retag_image ${image_tag} ${CIRCLE_SHA1} latest
workflows:
  version: 2
  commit:
    jobs:
      - docker-build-image
  
  scheduled-workflow:
    triggers:
      - schedule:
          cron: "0 12 * * 1"
          filters:
            branches:
              only:
                - main
    jobs:
      - docker-build-image
